include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  errors:
    argument_type_not_assignable: ignore
    non_bool_operand: ignore
    non_bool_condition: ignore
    return_of_invalid_type_from_closure: ignore

linter:
  rules:
    always_use_package_imports: true
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: false
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    avoid_dynamic_calls: false
    type_annotate_public_apis: false
    avoid_bool_literals_in_conditional_expressions: false
    require_trailing_commas: false
    sized_box_for_whitespace: true
    sort_pub_dependencies: true
    prefer_if_elements_to_conditional_expressions: false

